"""
state.py — TypedDict schema, strategy modes, and system prompt
for the Exam Preparation Strategy Agent.
"""

from typing import TypedDict, Optional, List, Dict
from enum import Enum


# ─────────────────────────────────────────────
# Strategy Mode Enum
# ─────────────────────────────────────────────

class StrategyMode(str, Enum):
    PROGRESSIVE = "Progressive Mastery Mode"
    INTENSIVE = "Intensive Revision Mode"


# ─────────────────────────────────────────────
# Subject Entry
# ─────────────────────────────────────────────

class SubjectEntry(TypedDict):
    name: str
    confidence: int          # 1–10 (1=low, 10=high)
    priority_label: str      # "High", "Mid", "Low"
    weight: float            # computed multiplier
    allocated_hours: float   # computed hours


# ─────────────────────────────────────────────
# Lifestyle Block
# ─────────────────────────────────────────────

class LifestyleBlock(TypedDict):
    wake_time: str           # "06:00"
    sleep_time: str          # "22:00"
    meal_slots: List[str]    # ["08:00-08:30", "13:00-13:30", "19:00-19:30"]
    routine_slots: List[str] # ["07:00-07:30"] (exercise, prayer, etc.)


# ─────────────────────────────────────────────
# Agent State (LangGraph shared state)
# ─────────────────────────────────────────────

class AgentState(TypedDict):
    # ── Inputs ──────────────────────────────
    subjects_raw: str                       # raw comma-separated subject string
    exam_date: str                          # "YYYY-MM-DD"
    daily_study_hours: float
    lifestyle: Optional[LifestyleBlock]
    syllabus_context: Optional[str]         # extracted docx text (optional)

    # ── Computed by tools.py ─────────────────
    days_remaining: int
    total_study_hours: float
    available_time_blocks: List[str]        # ["09:00-11:00", "14:00-16:00", ...]
    subjects: List[SubjectEntry]
    strategy_mode: StrategyMode

    # ── Generated by agent.py ────────────────
    strategy_explanation: str
    timetable: List[Dict]                   # day-wise plan dicts
    mini_goals: List[str]
    motivation_line: str
    final_output: str                       # rendered markdown output


# ─────────────────────────────────────────────
# System Prompt (fed to Gemini)
# ─────────────────────────────────────────────

SYSTEM_PROMPT = """
You are an expert academic planning agent specializing in optimizing student exam preparation.

Your role is to act as a constraint-aware, behavior-sensitive planning intelligence. You receive:
- A student's subjects with confidence scores and pre-computed hour allocations
- Days remaining until the exam
- The active strategy mode (Progressive Mastery or Intensive Revision)
- Available daily time blocks
- Optional syllabus context

Your responsibilities:
1. Generate a clear strategy explanation (2–3 sentences) that reflects the mode and constraints.
2. Produce a day-wise timetable plan where each day contains:
   - Date label (e.g., "Day 1 — Mon, 14 Jul")
   - Subject blocks with time and duration
   - One mini goal per study block (alternating educational and fun)
3. Add one motivational closing line.

CRITICAL RULES:
- Do NOT perform arithmetic. Hour allocations are already computed and provided to you.
- Trust the pre-computed allocations completely.
- In Intensive Revision Mode: prioritize high-priority subjects heavily, focus on past-paper practice.
- In Progressive Mastery Mode: rotate subjects, include a weekly revision checkpoint.
- Mini goals should alternate: one educational, one fun. Examples:
  - Educational: "Summarize Chapter 4 in 8 bullet points."
  - Fun: "Explain this topic to an imaginary goldfish. Yes, seriously."
- If syllabus context is provided, subtly weave the mentioned topics into relevant mini goals.
- Keep tone warm, energizing, and precise. Not overwhelming.
- Output must be clean, structured, and readable as markdown.
"""
